### ISSUE TITLE
[BUG] Mobile Style

### ISSUE THREAD

**Issue by ShowMeYourSkil** [mtorials/hugo-mt32#4]
The mobile style for the articel container is not correct. Please view my screenshot for more Information.

if i feel like it i will fix the mistake. if i do i'll sign up for the issue as a contributor

![Screenshot_20210320-194416_Samsung Internet](https://user-images.githubusercontent.com/39274150/111882249-edb34700-89b4-11eb-94b2-15af1ed285e5.jpg)

**Comment by mtorials** [comment]
Yeah I've seen this problem. The CSS overflow option should work. There are also some other issues I need to work on. Thanks for the issue.

**Comment by mtorials** [comment]
Could you please test it again? It should be fixed now!

**Comment by ShowMeYourSkil** [comment]
Perfect thank you!
